<?php

use App\ContentPage;
use App\Repos\IAboutType;
use App\Repos\ICouncilType;
use App\Repos\IPageType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentPageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('content_pages')->delete();

        $contentPages = array(
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutMandate, 'council_type' => '', 'content' => '<p>Emirates Cricket is the governing body for the sport of cricket in the United Arab Emirates. The Emirates Cricket Board is responsible for overseeing all aspects of play within the four councils, as well as in all other Emirates.&nbsp;<br><br>Emirates Cricket’s Councils include Abu Dhabi, Ajman, Dubai and Sharjah. The remaining Emirates under the Board are Fujairah, and Ras Al Khaimah.&nbsp;<br><br>Emirates Cricket is an Associate Member of the International Cricket Council (ICC).</p>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutAcademics, 'council_type' => '', 'content' => '<p>Cricket at a junior level is hugely popular in the UAE and is enjoyed by both boys and girls from 6 to 18 years old. The UAE is very fortunate to offer a number of recognized, high-quality cricket academies for those wishing to learn basic fundamentals or those wishing to fine-tune to the more demanding skills of the sport. While learning about cricket through these institutions, the next generation gains valuable insight and experience into enjoyment, camaraderie, participation, teamwork and commitment. Academies also provide the nurturing environment that is required for the up and coming stars at an international level.<br><br>The UAE Emirates Cricket Board is therefore committed to ensuring that the registered academies follow best practice principles in the delivery of their programmes. This includes ensuring that each academy is providing quality skill appropriate coaching, have health and safety protocols in place and providing access to a wide participation base.<br>
                &nbsp;<br>Where do you want to learn?</p><p><a href="#">Abu Dhabi </a>,&nbsp;<span style="line-height: 1.6;"><a href="#">Ajman</a>,&nbsp;</span><a href="#" style="line-height: 1.6;">Dubai </a>,&nbsp;<a href="#" style="line-height: 1.6;">Sharjah</a>,&nbsp;<a href="#"><span style="line-height: 1.6;">Other Emirates</span></a></p>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutEducation, 'council_type' => '', 'content' => '<p>Here are some of the education and downloads links for the Emirates Cricket Board including links to the International Cricket Councils key rules and regulations. Should you not be able to find the information you are looking for, please contact :<span style="color: rgb(38, 38, 38); font-family: arial, sans-serif; line-height: 16px;">&nbsp;</span><a class="Xx" data-display="info@emiratescricket.com" data-sanitized="mailto:info@emiratescricket.com" dir="ltr" href="mailto:info@emiratescricket.com" rel="nofollow noreferrer" style="unicode-bidi: -webkit-isolate; font-family: arial, sans-serif; line-height: 16px;" tabindex="-1" target="_blank">info@emiratescricket.com</a></p><h3>Rules and Regulations</h3><div class="sc_column_item sc_column_item_3 odd">
<ul class="sc_list sc_list_style_regular"><li class="sc_list_item even sc_list_style_mark"><span class="sc_list_icon"></span><a href="http://www.icc-cricket.com/cricket-rules-and-regulations" target="_blank">ICC Rules and Regulations</a></li></ul></div>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutRegionalCouncils, 'council_type' => ICouncilType::councilAbuDhabi, 'content' => '<p><img alt="" src="/uploads/files/images/abushabiCouncil.gif" style="width: 183px; height: 139px;"></p><p>Abu Dhabi Cricket Club (ADCC) has over 70 cricket clubs registered, with more joining every season. These teams play within a variety of tournaments sanctioned by ADCC where they also have access to the club\'s grounds at Sheikh Zayed Stadium, Abu Dhabi.</p><p>Cricket is one of the most-watched and most actively participated games in the UAE and Abu Dhabi Cricket Club (ADDC) is proud to be at the heart of it. Over 500 amateur matches were played at the Zayed Stadium and ADCC grounds during the 2014/2105 season.&nbsp;</p><p>Apart from hosting several international matches within the last 12 months, it has been the growth of the amateur competition in recent seasons that has been of great encouragement to all involved in cricket in the region.</p><p>For more information visit <a href="http://www.adcricketclub.ae/" target="_blank">http://www.adcricketclub.ae/</a> or email - <a href="mailto:info@adcricketclub.ae">info@adcricketclub.ae</a></p>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutRegionalCouncils, 'council_type' => ICouncilType::councilDubai, 'content' => '<p><img alt="" src="/uploads/files/images/councilLogoDubai.jpg" style="width: 200px; height: 181px;"></p><p>The Dubai Cricket Council (DCC) is responsible forfor conducting, promoting and scheduling the game of cricket and providing amenities to those who wish to learn the art of play and continue playing the game within the Emirate of Dubai.</p><p>DCC is licensed for its activities by Department of Economic Development, Government of Dubai and is an affiliate of the Emirates Cricket Board, the national body created by Ministry of Youth and Sports in 1989.</p><p>Dubai Cricket Council’s newly opening HO is located at the Park Avenue Office Building in Dubai Silicon Oasis.</p><p>For more information visit <a href="https://www.facebook.com/pages/Dubai-Cricket-Council-DCC/131110423627306" target="_blank">https://www.facebook.com/pages/Dubai-Cricket-Council-DCC/131110423627306</a></p>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutRegionalCouncils, 'council_type' => ICouncilType::councilSharjah, 'content' => '<p><img alt="" src="/uploads/files/images/Sharjah-Cricket-Council.png" style="width: 300px; height: 200px;"></p><p>Sharjah Cricket Council (SCC) is one of the 4 recognised cricket councils under the Emirates Cricket Board. SCC is engaged in all aspects and activities relating to the growth, promotion and governance of the game in Sharjah.</p><p>At domestic level, the Sharjah Cricket Council has over 32 cricket club’s registered, and with the home ground being the highly popular Sharjah Cricket Stadium, this number continues to grow.</p><p>Sharjah Cricket Council is located at the world-renowned Sharjah Cricket Stadium, home of the Pakistan Cricket Team and which regularly sees International greats such as Australia, England, India, and of course Pakistan play at this stadium.</p><p>for more information visit <a href="http://sharjahcricket.ae" target="_blank">http://sharjahcricket.ae</a> or email - <a href="mailto:scc_cric@emirates.net.ae">scc_cric@emirates.net.ae</a></p>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutRegionalCouncils, 'council_type' => ICouncilType::councilAjman, 'content' => '<p>For more information on the Ajman Cricket Council please contact :&nbsp;<a href="http://ajmancricketcouncil.com">http://ajmancricketcouncil.com</a></p>'),
            array('page_type' => IPageType::aboutPage, 'about_type' => IAboutType::aboutChairmanMessage, 'council_type' => '', 'content' => '<p>Cricket in the UAE enjoys a strong, illustrious history and continues to be a well-supported and popular sport played across the UAE since being introduced to our shores over 80-years ago. During that time, we have enjoyed seeing the sport grow to where, today, we have over 3,000 active amateur teams,&nbsp;50&nbsp;registered academies, and enjoy seeing well over 90,000 individuals actively involved in the game. Our Men’s, Women’s and U19 representative teams continue to excel in their performances on the international stage in both Asian Cricket Council and ICC tournaments.<br>Emirates Cricket boasts a strong Domestic portfolio through the D10, D20 and D50 series, as well as our Inter-Emirate Age-Group tournament. We are extremely proud to have added our own International UAE T20 League to our annual calendar. Our Board is very proactive in supporting the various Council-managed tournaments such as the long-standing, popular Bukhatir Premier League, the exciting Abu Dhabi T10 format as well as many other tournaments and series.<br>The UAE itself has fast become the international destination of choice for numerous top-tiered tournaments, such as the IPL, PSL, ICC Cricket World Cup, Asian Cricket Council U19 Asia Cup and various ICC Qualifying events. Our three World-Class stadia; located in Abu Dhabi, Dubai and Sharjah, regularly welcome various Full-Member and Associate-Member training camps throughout the season.<br>Emirates Cricket, having achieved ICC Associate Member status in 1990, continues to work tirelessly to maintain its standing and recognition as a leading Associate within the ICC. This recognition has been achieved through the unwavering support of councils; Abu Dhabi Cricket, Ajman Cricket, Dubai Cricket and Sharjah Cricket, the strong cricket-community in Fujairah, Umm Al Quwain&nbsp;and Ras Al Khaimah, our leaders and the people of the United Arab Emirates, we, on the Emirates Cricket Board, are proud of the reputation we uphold and the benchmark we establish and maintain.</p>')
        );

        ContentPage::insert($contentPages);
    }
}
