<?php

use App\Development;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DevelopmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('developments')->delete();

        $records = array(
            array('title' => 'Introduction', 'type' => Development::$Introduction, 'heading' => '<p>Emirates Cricket has a number of successful stand-alone tournaments in our National structure and calendar which are focused toward identifying and integrating players into Emirates Cricket’s talent identification process, and, in turn, bolster our representative team player pool.</p><p>Each training program and tournament within the Development Program structure is overseen by the Emirates Cricket Development and High Performance teams.</p><p>For more detailed information about Emirates Cricket’s Development Calendar and Program contact <a href="mailto:info@emiratescricket.com">info@emiratescricket.com</a></p>', 'description' => '<p>Emirates Cricket has a number of successful stand-alone tournaments in our National structure and calendar which are focused toward identifying and integrating players into Emirates Cricket’s talent identification process, and, in turn, bolster our representative team player pool.</p><p>Each training program and tournament within the Development Program structure is overseen by the Emirates Cricket Development and High Performance teams.</p><p>For more detailed information about Emirates Cricket’s Development Calendar and Program contact <a href="mailto:info@emiratescricket.com">info@emiratescricket.com</a></p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()),
            array('title' => 'Domestic Men’s Series - D10, D20 and D50', 'type' => Development::$DomesticMen, 'heading' => '<p>Conceptualised to discover unique home-grown talent across the 10-over, 20-over and 50-over formats, the Emirates Cricket Domestic Series sees the Emirates Cricket Head Coach / Director of Cricket work closely with the Councils to put forward a solid mix of youth and first class players to compete at a National-level, where players are provided with the experience to hone their skills and for the Development and High Performance teams to identify areas of growth. These tournaments are an integral vehicle for UAE to ensure there is a solid pathway and succession plan in place to compete at Regional and International levels.</p>', 'description' => '<p>Conceptualised to discover unique home-grown talent across the 10-over, 20-over and 50-over formats, the Emirates Cricket Domestic Series sees the Emirates Cricket Head Coach / Director of Cricket work closely with the Councils to put forward a solid mix of youth and first class players to compete at a National-level, where players are provided with the experience to hone their skills and for the Development and High Performance teams to identify areas of growth. These tournaments are an integral vehicle for UAE to ensure there is a solid pathway and succession plan in place to compete at Regional and International levels.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()),
            array('title' => 'Women’s', 'type' => Development::$Women, 'heading' => '<p>The women’s development calendar aims to introduce the game to all levels of athletic-minded girls across the Emirates, and provide a strong pathway for players recommended by the Councils and recognised by the Development and High Performance teams. Through regularly hosted girls-only skill camps to short-format tournaments held throughout the season, overseen by Emirates Cricket, these programs and tournaments are vital in Emirates Cricket’s commitment to growing the Women’s game across our region.</p>', 'description' => '<p>The women’s development calendar aims to introduce the game to all levels of athletic-minded girls across the Emirates, and provide a strong pathway for players recommended by the Councils and recognised by the Development and High Performance teams. Through regularly hosted girls-only skill camps to short-format tournaments held throughout the season, overseen by Emirates Cricket, these programs and tournaments are vital in Emirates Cricket’s commitment to growing the Women’s game across our region.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()),
            array('title' => 'Inter-Emirates League – Boys Age group', 'type' => Development::$InterEmiratesLeague, 'heading' => '<p>Emirates Cricket’s Inter-Emirate League is an exciting program which provides a platform for the best junior cricketers, who are actively playing in each Councils’ tournaments and leagues structure, to perform at a National-level as well as to recognise their own potential. Hosted annually the tournament highlights the ‘Best of the Best’ 14 to 19-year old male players on offer.</p>', 'description' => '<p>Emirates Cricket’s Inter-Emirate League is an exciting program which provides a platform for the best junior cricketers, who are actively playing in each Councils’ tournaments and leagues structure, to perform at a National-level as well as to recognise their own potential. Hosted annually the tournament highlights the ‘Best of the Best’ 14 to 19-year old male players on offer.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()),
            array('title' => 'Emirati Development Program', 'type' => Development::$EmiratiDevelopment, 'heading' => '<p>Emirates Cricket is extremely cognisant in its responsibility to develop the Emirati youth into the game and has a robust schools-program in place. The Development Team works closely with the Ministry of Education to deliver these skills and fitness sessions to the youth at Emirati-schools, across the region, throughout the School season.</p>', 'description' => '<p>Emirates Cricket is extremely cognisant in its responsibility to develop the Emirati youth into the game and has a robust schools-program in place. The Development Team works closely with the Ministry of Education to deliver these skills and fitness sessions to the youth at Emirati-schools, across the region, throughout the School season.</p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()),
            array('title' => 'Development Pathway', 'type' => Development::$DevelopmentPathway, 'heading' => '<p>The UAE Women’s team is the team that represents the United Arab Emirates (UAE) in international and regional cricket matches. In July 2007, the UAE Women’s team made their international debut in the Asian Cricket Council’s (ACC) Women’s Tournament, which was played in Malaysia.</p>', 'description' => '<p>We want the game of cricket to be as accessible as possible to everyone living in the UAE.</p><p>Emirates Cricket has worked very hard in creating a comprehensive player pathway in which every player, no matter their skill set, gender or race can participate and grow in the game of cricket.</p><p>We believe the development pathway provides a unique opportunity to progress from grass roots cricket to potentially becoming a UAE National player and provides a player with some clarity on where they fit in.</p><p>The development pathway is about letting everyone know where their opportunities lie in cricket and how we, Emirates Cricket, can help progress their involvement in the game.</p><p>The pathway has a strong focus on talent identification and includes the important new initiatives of the National Inter Council U16, U19 and Open tournaments. These tournaments allow the best players from the region to represent their emirate for possible national team selection.</p><p>In addition to this, plans are underway in creating a national academy to support the talent identification aspect of the programme. For more information about the Development Pathway contact Emirates Cricket’s National Development Manager, Andrew Russell via email: <a href="mailto:andrew.russell@emiratescricket.com">andrew.russell@emiratescricket.com</a></p>', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()),
        );

        DB::table('developments')->insert($records);
    }
}
